name: Continuous Integration

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required dependencies
        run: |
          sudo apt-get update -qq && sudo apt-get -y install \
          autoconf \
          automake \
          build-essential \
          cmake \
          git-core \
          libass-dev \
          libfreetype6-dev \
          libgnutls28-dev \
          libmp3lame-dev \
          libsdl2-dev \
          libtool \
          libva-dev \
          libvdpau-dev \
          libvorbis-dev \
          libxcb1-dev \
          libxcb-shm0-dev \
          libxcb-xfixes0-dev \
          meson \
          ninja-build \
          pkg-config \
          texinfo \
          wget \
          yasm \
          zlib1g-dev \
          libunistring-dev \
          libaom-dev \
          libdav1d-dev
      - name: Creating build directory
        run: mkdir -p ~/ffmpeg_sources ~/bin
      - name: Install optional dependencies
        run: |
          sudo apt-get install \
          nasm \
          libx264-dev \
          libx265-dev \
          libnuma-dev \
          libvpx-dev \
          libfdk-aac-dev \
          libopus-dev \
          libdav1d-dev \
          libsvtav1-dev \
          libsvtav1enc-dev \
          libsvtav1dec-dev \
          libbluray-dev \
          libgsm1-dev
      - name: Install libsvtav1
        run: |
          cd ~/ffmpeg_sources && \
          git -C SVT-AV1 pull 2> /dev/null || git clone https://gitlab.com/AOMediaCodec/SVT-AV1.git && \
          mkdir -p SVT-AV1/build && \
          cd SVT-AV1/build && \
          PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DCMAKE_BUILD_TYPE=Release -DBUILD_DEC=OFF -DBUILD_SHARED_LIBS=OFF .. && \
          PATH="$HOME/bin:$PATH" make && \
          make install
      - name: Install libvmaf
        run: |
          cd ~/ffmpeg_sources && \
          wget https://github.com/Netflix/vmaf/archive/v3.0.0.tar.gz && \
          tar xvf v3.0.0.tar.gz && \
          mkdir -p vmaf-3.0.0/libvmaf/build &&\
          cd vmaf-3.0.0/libvmaf/build && \
          meson setup -Denable_tests=false -Denable_docs=false --buildtype=release --default-library=static .. --prefix "$HOME/ffmpeg_build" --bindir="$HOME/ffmpeg_build/bin" --libdir="$HOME/ffmpeg_build/lib" && \
          ninja && \
          ninja install
          mv $HOME/ffmpeg_build/bin/* $HOME/bin/
      - name: Building FFmpeg
        run: |
          cd ~/ffmpeg_sources && \
          wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
          tar xjvf ffmpeg-snapshot.tar.bz2 && \
          cd ffmpeg && \
          PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
            --prefix="$HOME/ffmpeg_build" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$HOME/ffmpeg_build/include" \
            --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
            --extra-libs="-lpthread -lm" \
            --ld="g++" \
            --bindir="$HOME/bin" \
            --enable-fontconfig \
            --enable-gpl \
            --enable-libaom \
            --enable-libass \
            --enable-libbluray \
            --enable-libdav1d \
            --enable-libfreetype \
            --enable-libgsm \
            --enable-libharfbuzz \
            --enable-libmodplug \
            --enable-libmp3lame \
            --enable-libmysofa \
            --enable-libopencore-amrnb \
            --enable-libopencore-amrwb \
            --enable-libopenh264 \
            --enable-libopenjpeg \
            --enable-libopus \
            --enable-librubberband \
            --enable-libshine \
            --enable-libsnappy \
            --enable-libsoxr \
            --enable-libspeex \
            --enable-libtheora \
            --enable-libtwolame \
            --enable-libvidstab \
            --enable-libvmaf \
            --enable-libvo-amrwbenc \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libwebp \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libxavs \
            --enable-libxml2 \
            --enable-libxvid \
            --enable-libzimg \
            --enable-libzmq \
            --enable-libzvbi \
            --disable-videotoolbox \
            --enable-version3 \
            --disable-ffplay && \
          PATH="$HOME/bin:$PATH" make && \
          make install && \
          hash -r
      - name: Test installation
        run: source ~/.profile && ffmpeg -version
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install FFmpeg
        run: sudo apt update && sudo apt install ffmpeg -y
      - name: Verify FFmpeg installation
        run: ffmpeg -version
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install test dependencies
        run: pip install -e .[test]
      - name: Perform test
        run: pytest
  Quality:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install lint dependencies
        run: pip install -e .[lint]
      - name: Perform lint
        run: flake8